version: "3"
services:
  structuring_pairs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo_database
  mongo_database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      -
