import * as func_arbitrage from "./func_arbitrage";
import axios from "axios";
import { TPair } from "./func_arbitrage";
import { PricesJson, DepthInfo } from "./func_arbitrage";
import { MongoClient } from "mongodb";
import express, { Request, Response } from "express";

const app = express();
const port = 3001;
let real_rate_dict: DepthInfo | { "realRatePerc < -1": string };

app.get("/", async (req: Request, res: Response) => {
  try {
    const real_rate_dict = await step_1();
    if (real_rate_dict) {
      res.status(200).json(real_rate_dict);
    } else {
      res.status(404).json({ message: "pas de real_rate_dict" });
    }
  } catch (error) {
    console.error("Erreur lors de la récupération de real_rate_dict :", error);
    res.status(500).json({
      error: "Erreur lors de la récupération de real_rate_dict",
    });
  }
});

// Endpoint pour récupérer l'opportunité réelle
app.get("/real-opportunity", async (req: Request, res: Response) => {
  try {
    const real_rate_dict = await step_1();
    if (
      real_rate_dict &&
      "real_rate_perc" in real_rate_dict &&
      real_rate_dict.real_rate_perc > 0
    ) {
      res.status(200).json(real_rate_dict);
    } else {
      res.status(404).json({ message: "Aucune opportunité réelle trouvée" });
    }
  } catch (error) {
    console.error(
      "Erreur lors de la récupération de l'opportunité réelle :",
      error
    );
    res.status(500).json({
      error: "Erreur lors de la récupération de l'opportunité réelle",
    });
  }
});

const mongoURI = "mongodb://localhost:27017";
const dbName = "mydb";
const client = new MongoClient(mongoURI);

const structured_pairs_url: string = "http://localhost:3000/triangularpairs";
const prices_url: string = "http://localhost:3000/prices";
let structured_pairs: any[];

async function step_0(): Promise<void> {
  try {
    const response = await axios.get(structured_pairs_url);
    if (response.status === 200) {
      structured_pairs = response.data;
      console.log("Structured pairs:", structured_pairs);
    } else {
      throw new Error("Failed to fetch structured pairs");
    }
  } catch (error: any) {
    console.error("Error fetching structured pairs:", error.message);
  }
}

// step_0 for stuctured pairs
//const structured_pairs: TPair[] = await step_0();
structured_pairs = [
  {
    a_base: "BTS",
    b_base: "BTC",
    c_base: "BTS",
    a_quote: "BTC",
    b_quote: "USDT",
    c_quote: "USDT",
    pair_a: "BTS_BTC",
    pair_b: "BTC_USDT",
    pair_c: "BTS_USDT",
    triangular_pair: "BTC_USDT BTS_BTC BTS_USDT",
  },
  {
    a_base: "DASH",
    b_base: "BTC",
    c_base: "DASH",
    a_quote: "BTC",
    b_quote: "USDT",
    c_quote: "USDT",
    pair_a: "DASH_BTC",
    pair_b: "BTC_USDT",
    pair_c: "DASH_USDT",
    triangular_pair: "BTC_USDT DASH_BTC DASH_USDT",
  },
  {
    a_base: "DASH",
    b_base: "BTC",
    c_base: "DASH",
    a_quote: "BTC",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "DASH_BTC",
    pair_b: "BTC_USDC",
    pair_c: "DASH_USDC",
    triangular_pair: "BTC_USDC DASH_BTC DASH_USDC",
  },
  {
    a_base: "DOGE",
    b_base: "BTC",
    c_base: "DOGE",
    a_quote: "BTC",
    b_quote: "USDT",
    c_quote: "USDT",
    pair_a: "DOGE_BTC",
    pair_b: "BTC_USDT",
    pair_c: "DOGE_USDT",
    triangular_pair: "BTC_USDT DOGE_BTC DOGE_USDT",
  },
  {
    a_base: "DOGE",
    b_base: "BTC",
    c_base: "DOGE",
    a_quote: "BTC",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "DOGE_BTC",
    pair_b: "BTC_USDC",
    pair_c: "DOGE_USDC",
    triangular_pair: "BTC_USDC DOGE_BTC DOGE_USDC",
  },
  {
    a_base: "DOGE",
    b_base: "BTC",
    c_base: "DOGE",
    a_quote: "BTC",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "DOGE_BTC",
    pair_b: "BTC_USDD",
    pair_c: "DOGE_USDD",
    triangular_pair: "BTC_USDD DOGE_BTC DOGE_USDD",
  },
  {
    a_base: "LTC",
    b_base: "BTC",
    c_base: "LTC",
    a_quote: "BTC",
    b_quote: "USDT",
    c_quote: "USDT",
    pair_a: "LTC_BTC",
    pair_b: "BTC_USDT",
    pair_c: "LTC_USDT",
    triangular_pair: "BTC_USDT LTC_BTC LTC_USDT",
  },
  {
    a_base: "LTC",
    b_base: "BTC",
    c_base: "LTC",
    a_quote: "BTC",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "LTC_BTC",
    pair_b: "BTC_USDC",
    pair_c: "LTC_USDC",
    triangular_pair: "BTC_USDC LTC_BTC LTC_USDC",
  },
  {
    a_base: "LTC",
    b_base: "BTC",
    c_base: "LTC",
    a_quote: "BTC",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "LTC_BTC",
    pair_b: "BTC_USDD",
    pair_c: "LTC_USDD",
    triangular_pair: "BTC_USDD LTC_BTC LTC_USDD",
  },
  {
    a_base: "XLM",
    b_base: "BTC",
    c_base: "XLM",
    a_quote: "BTC",
    b_quote: "USDT",
    c_quote: "USDT",
    pair_a: "XLM_BTC",
    pair_b: "BTC_USDT",
    pair_c: "XLM_USDT",
    triangular_pair: "BTC_USDT XLM_BTC XLM_USDT",
  },
  {
    a_base: "XLM",
    b_base: "BTC",
    c_base: "XLM",
    a_quote: "BTC",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "XLM_BTC",
    pair_b: "BTC_USDC",
    pair_c: "XLM_USDC",
    triangular_pair: "BTC_USDC XLM_BTC XLM_USDC",
  },
  {
    a_base: "XEM",
    b_base: "BTC",
    c_base: "XEM",
    a_quote: "BTC",
    b_quote: "USDT",
    c_quote: "USDT",
    pair_a: "XEM_BTC",
    pair_b: "BTC_USDT",
    pair_c: "XEM_USDT",
    triangular_pair: "BTC_USDT XEM_BTC XEM_USDT",
  },
  {
    a_base: "XEM",
    b_base: "BTC",
    c_base: "XEM",
    a_quote: "BTC",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "XEM_BTC",
    pair_b: "BTC_USDC",
    pair_c: "XEM_USDC",
    triangular_pair: "BTC_USDC XEM_BTC XEM_USDC",
  },
  {
    a_base: "XMR",
    b_base: "BTC",
    c_base: "XMR",
    a_quote: "BTC",
    b_quote: "USDT",
    c_quote: "USDT",
    pair_a: "XMR_BTC",
    pair_b: "BTC_USDT",
    pair_c: "XMR_USDT",
    triangular_pair: "BTC_USDT XMR_BTC XMR_USDT",
  },
  {
    a_base: "XMR",
    b_base: "BTC",
    c_base: "XMR",
    a_quote: "BTC",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "XMR_BTC",
    pair_b: "BTC_USDC",
    pair_c: "XMR_USDC",
    triangular_pair: "BTC_USDC XMR_BTC XMR_USDC",
  },
  {
    a_base: "XRP",
    b_base: "BTC",
    c_base: "XRP",
    a_quote: "BTC",
    b_quote: "USDT",
    c_quote: "USDT",
    pair_a: "XRP_BTC",
    pair_b: "BTC_USDT",
    pair_c: "XRP_USDT",
    triangular_pair: "BTC_USDT XRP_BTC XRP_USDT",
  },
  {
    a_base: "XRP",
    b_base: "BTC",
    c_base: "XRP",
    a_quote: "BTC",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "XRP_BTC",
    pair_b: "BTC_USDC",
    pair_c: "XRP_USDC",
    triangular_pair: "BTC_USDC XRP_BTC XRP_USDC",
  },
  {
    a_base: "XRP",
    b_base: "TRX",
    c_base: "XRP",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "XRP_BTC",
    pair_b: "TRX_BTC",
    pair_c: "XRP_TRX",
    triangular_pair: "TRX_BTC XRP_BTC XRP_TRX",
  },
  {
    a_base: "XRP",
    b_base: "BTC",
    c_base: "XRP",
    a_quote: "BTC",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "XRP_BTC",
    pair_b: "BTC_USDD",
    pair_c: "XRP_USDD",
    triangular_pair: "BTC_USDD XRP_BTC XRP_USDD",
  },
  {
    a_base: "BTC",
    b_base: "ETH",
    c_base: "ETH",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "ETH_BTC",
    pair_c: "ETH_USDT",
    triangular_pair: "BTC_USDT ETH_BTC ETH_USDT",
  },
  {
    a_base: "BTC",
    b_base: "SC",
    c_base: "SC",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "SC_BTC",
    pair_c: "SC_USDT",
    triangular_pair: "BTC_USDT SC_BTC SC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "DCR",
    c_base: "DCR",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "DCR_BTC",
    pair_c: "DCR_USDT",
    triangular_pair: "BTC_USDT DCR_BTC DCR_USDT",
  },
  {
    a_base: "BTC",
    b_base: "LSK",
    c_base: "LSK",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "LSK_BTC",
    pair_c: "LSK_USDT",
    triangular_pair: "BTC_USDT LSK_BTC LSK_USDT",
  },
  {
    a_base: "BTC",
    b_base: "STEEM",
    c_base: "STEEM",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "STEEM_BTC",
    pair_c: "STEEM_USDT",
    triangular_pair: "BTC_USDT STEEM_BTC STEEM_USDT",
  },
  {
    a_base: "BTC",
    b_base: "ETC",
    c_base: "ETC",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "ETC_BTC",
    pair_c: "ETC_USDT",
    triangular_pair: "BTC_USDT ETC_BTC ETC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "ARDR",
    c_base: "ARDR",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "ARDR_BTC",
    pair_c: "ARDR_USDT",
    triangular_pair: "ARDR_BTC ARDR_USDT BTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "ZEC",
    c_base: "ZEC",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "ZEC_BTC",
    pair_c: "ZEC_USDT",
    triangular_pair: "BTC_USDT ZEC_BTC ZEC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "ZRX",
    c_base: "ZRX",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "ZRX_BTC",
    pair_c: "ZRX_USDT",
    triangular_pair: "BTC_USDT ZRX_BTC ZRX_USDT",
  },
  {
    a_base: "BTC",
    b_base: "CVC",
    c_base: "CVC",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "CVC_BTC",
    pair_c: "CVC_USDT",
    triangular_pair: "BTC_USDT CVC_BTC CVC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "OMG",
    c_base: "OMG",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "OMG_BTC",
    pair_c: "OMG_USDT",
    triangular_pair: "BTC_USDT OMG_BTC OMG_USDT",
  },
  {
    a_base: "BTC",
    b_base: "GAS",
    c_base: "GAS",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "GAS_BTC",
    pair_c: "GAS_USDT",
    triangular_pair: "BTC_USDT GAS_BTC GAS_USDT",
  },
  {
    a_base: "BTC",
    b_base: "STORJ",
    c_base: "STORJ",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "STORJ_BTC",
    pair_c: "STORJ_USDT",
    triangular_pair: "BTC_USDT STORJ_BTC STORJ_USDT",
  },
  {
    a_base: "BTC",
    b_base: "EOS",
    c_base: "EOS",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "EOS_BTC",
    pair_c: "EOS_USDT",
    triangular_pair: "BTC_USDT EOS_BTC EOS_USDT",
  },
  {
    a_base: "BTC",
    b_base: "SNT",
    c_base: "SNT",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "SNT_BTC",
    pair_c: "SNT_USDT",
    triangular_pair: "BTC_USDT SNT_BTC SNT_USDT",
  },
  {
    a_base: "BTC",
    b_base: "KNC",
    c_base: "KNC",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "KNC_BTC",
    pair_c: "KNC_USDT",
    triangular_pair: "BTC_USDT KNC_BTC KNC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "BAT",
    c_base: "BAT",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "BAT_BTC",
    pair_c: "BAT_USDT",
    triangular_pair: "BAT_BTC BAT_USDT BTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "LOOM",
    c_base: "LOOM",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "LOOM_BTC",
    pair_c: "LOOM_USDT",
    triangular_pair: "BTC_USDT LOOM_BTC LOOM_USDT",
  },
  {
    a_base: "BTC",
    b_base: "QTUM",
    c_base: "QTUM",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "QTUM_BTC",
    pair_c: "QTUM_USDT",
    triangular_pair: "BTC_USDT QTUM_BTC QTUM_USDT",
  },
  {
    a_base: "BTC",
    b_base: "BTC",
    c_base: "USDT",
    a_quote: "USDT",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "BTC_USDT",
    pair_b: "BTC_USDC",
    pair_c: "USDT_USDC",
    triangular_pair: "BTC_USDC BTC_USDT USDT_USDC",
  },
  {
    a_base: "BTC",
    b_base: "MANA",
    c_base: "MANA",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "MANA_BTC",
    pair_c: "MANA_USDT",
    triangular_pair: "BTC_USDT MANA_BTC MANA_USDT",
  },
  {
    a_base: "BTC",
    b_base: "BNT",
    c_base: "BNT",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "BNT_BTC",
    pair_c: "BNT_USDT",
    triangular_pair: "BNT_BTC BNT_USDT BTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "BCHSV",
    c_base: "BCHSV",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "BCHSV_BTC",
    pair_c: "BCHSV_USDT",
    triangular_pair: "BCHSV_BTC BCHSV_USDT BTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "NMR",
    c_base: "NMR",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "NMR_BTC",
    pair_c: "NMR_USDT",
    triangular_pair: "BTC_USDT NMR_BTC NMR_USDT",
  },
  {
    a_base: "BTC",
    b_base: "POLY",
    c_base: "POLY",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "POLY_BTC",
    pair_c: "POLY_USDT",
    triangular_pair: "BTC_USDT POLY_BTC POLY_USDT",
  },
  {
    a_base: "BTC",
    b_base: "LPT",
    c_base: "LPT",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "LPT_BTC",
    pair_c: "LPT_USDT",
    triangular_pair: "BTC_USDT LPT_BTC LPT_USDT",
  },
  {
    a_base: "BTC",
    b_base: "ATOM",
    c_base: "ATOM",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "ATOM_BTC",
    pair_c: "ATOM_USDT",
    triangular_pair: "ATOM_BTC ATOM_USDT BTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "TRX",
    c_base: "TRX",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "TRX_BTC",
    pair_c: "TRX_USDT",
    triangular_pair: "BTC_USDT TRX_BTC TRX_USDT",
  },
  {
    a_base: "BTC",
    b_base: "LINK",
    c_base: "LINK",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "LINK_BTC",
    pair_c: "LINK_USDT",
    triangular_pair: "BTC_USDT LINK_BTC LINK_USDT",
  },
  {
    a_base: "BTC",
    b_base: "XTZ",
    c_base: "XTZ",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "XTZ_BTC",
    pair_c: "XTZ_USDT",
    triangular_pair: "BTC_USDT XTZ_BTC XTZ_USDT",
  },
  {
    a_base: "BTC",
    b_base: "SNX",
    c_base: "SNX",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "SNX_BTC",
    pair_c: "SNX_USDT",
    triangular_pair: "BTC_USDT SNX_BTC SNX_USDT",
  },
  {
    a_base: "BTC",
    b_base: "MATIC",
    c_base: "MATIC",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "MATIC_BTC",
    pair_c: "MATIC_USDT",
    triangular_pair: "BTC_USDT MATIC_BTC MATIC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "MKR",
    c_base: "MKR",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "MKR_BTC",
    pair_c: "MKR_USDT",
    triangular_pair: "BTC_USDT MKR_BTC MKR_USDT",
  },
  {
    a_base: "BTC",
    b_base: "NEO",
    c_base: "NEO",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "NEO_BTC",
    pair_c: "NEO_USDT",
    triangular_pair: "BTC_USDT NEO_BTC NEO_USDT",
  },
  {
    a_base: "BTC",
    b_base: "SWFTC",
    c_base: "SWFTC",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "SWFTC_BTC",
    pair_c: "SWFTC_USDT",
    triangular_pair: "BTC_USDT SWFTC_BTC SWFTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "AVA",
    c_base: "AVA",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "AVA_BTC",
    pair_c: "AVA_USDT",
    triangular_pair: "AVA_BTC AVA_USDT BTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "CHR",
    c_base: "CHR",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "CHR_BTC",
    pair_c: "CHR_USDT",
    triangular_pair: "BTC_USDT CHR_BTC CHR_USDT",
  },
  {
    a_base: "BTC",
    b_base: "BTC",
    c_base: "BNB",
    a_quote: "USDT",
    b_quote: "BNB",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "BTC_BNB",
    pair_c: "BNB_USDT",
    triangular_pair: "BNB_USDT BTC_BNB BTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "MDT",
    c_base: "MDT",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "MDT_BTC",
    pair_c: "MDT_USDT",
    triangular_pair: "BTC_USDT MDT_BTC MDT_USDT",
  },
  {
    a_base: "BTC",
    b_base: "REN",
    c_base: "REN",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "REN_BTC",
    pair_c: "REN_USDT",
    triangular_pair: "BTC_USDT REN_BTC REN_USDT",
  },
  {
    a_base: "BTC",
    b_base: "LRC",
    c_base: "LRC",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "LRC_BTC",
    pair_c: "LRC_USDT",
    triangular_pair: "BTC_USDT LRC_BTC LRC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "WRX",
    c_base: "WRX",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "WRX_BTC",
    pair_c: "WRX_USDT",
    triangular_pair: "BTC_USDT WRX_BTC WRX_USDT",
  },
  {
    a_base: "BTC",
    b_base: "SXP",
    c_base: "SXP",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "SXP_BTC",
    pair_c: "SXP_USDT",
    triangular_pair: "BTC_USDT SXP_BTC SXP_USDT",
  },
  {
    a_base: "BTC",
    b_base: "STPT",
    c_base: "STPT",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "STPT_BTC",
    pair_c: "STPT_USDT",
    triangular_pair: "BTC_USDT STPT_BTC STPT_USDT",
  },
  {
    a_base: "BTC",
    b_base: "SWAP",
    c_base: "SWAP",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "SWAP_BTC",
    pair_c: "SWAP_USDT",
    triangular_pair: "BTC_USDT SWAP_BTC SWAP_USDT",
  },
  {
    a_base: "BTC",
    b_base: "SWINGBY",
    c_base: "SWINGBY",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "SWINGBY_BTC",
    pair_c: "SWINGBY_USDT",
    triangular_pair: "BTC_USDT SWINGBY_BTC SWINGBY_USDT",
  },
  {
    a_base: "BTC",
    b_base: "DOT",
    c_base: "DOT",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "BTC",
    pair_a: "BTC_USDT",
    pair_b: "DOT_USDT",
    pair_c: "DOT_BTC",
    triangular_pair: "BTC_USDT DOT_BTC DOT_USDT",
  },
  {
    a_base: "BTC",
    b_base: "FCT2",
    c_base: "FCT2",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "BTC",
    pair_a: "BTC_USDT",
    pair_b: "FCT2_USDT",
    pair_c: "FCT2_BTC",
    triangular_pair: "BTC_USDT FCT2_BTC FCT2_USDT",
  },
  {
    a_base: "BTC",
    b_base: "FUND",
    c_base: "FUND",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "BTC",
    pair_a: "BTC_USDT",
    pair_b: "FUND_USDT",
    pair_c: "FUND_BTC",
    triangular_pair: "BTC_USDT FUND_BTC FUND_USDT",
  },
  {
    a_base: "BTC",
    b_base: "AKRO",
    c_base: "AKRO",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "BTC",
    pair_a: "BTC_USDT",
    pair_b: "AKRO_USDT",
    pair_c: "AKRO_BTC",
    triangular_pair: "AKRO_BTC AKRO_USDT BTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "REPV2",
    c_base: "REPV2",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "REPV2_BTC",
    pair_c: "REPV2_USDT",
    triangular_pair: "BTC_USDT REPV2_BTC REPV2_USDT",
  },
  {
    a_base: "BTC",
    b_base: "AMP",
    c_base: "AMP",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "AMP_BTC",
    pair_c: "AMP_USDT",
    triangular_pair: "AMP_BTC AMP_USDT BTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "SAND",
    c_base: "SAND",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "SAND_BTC",
    pair_c: "SAND_USDT",
    triangular_pair: "BTC_USDT SAND_BTC SAND_USDT",
  },
  {
    a_base: "BTC",
    b_base: "AAVE",
    c_base: "AAVE",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "AAVE_BTC",
    pair_c: "AAVE_USDT",
    triangular_pair: "AAVE_BTC AAVE_USDT BTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "INJ",
    c_base: "INJ",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "INJ_BTC",
    pair_c: "INJ_USDT",
    triangular_pair: "BTC_USDT INJ_BTC INJ_USDT",
  },
  {
    a_base: "BTC",
    b_base: "BCH",
    c_base: "BCH",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "BCH_BTC",
    pair_c: "BCH_USDT",
    triangular_pair: "BCH_BTC BCH_USDT BTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "SENSO",
    c_base: "SENSO",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "SENSO_BTC",
    pair_c: "SENSO_USDT",
    triangular_pair: "BTC_USDT SENSO_BTC SENSO_USDT",
  },
  {
    a_base: "BTC",
    b_base: "GLM",
    c_base: "GLM",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "GLM_BTC",
    pair_c: "GLM_USDT",
    triangular_pair: "BTC_USDT GLM_BTC GLM_USDT",
  },
  {
    a_base: "BTC",
    b_base: "WBTC",
    c_base: "WBTC",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "WBTC_BTC",
    pair_c: "WBTC_USDT",
    triangular_pair: "BTC_USDT WBTC_BTC WBTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "FRONT",
    c_base: "FRONT",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "FRONT_BTC",
    pair_c: "FRONT_USDT",
    triangular_pair: "BTC_USDT FRONT_BTC FRONT_USDT",
  },
  {
    a_base: "BTC",
    b_base: "FARM",
    c_base: "FARM",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "FARM_BTC",
    pair_c: "FARM_USDT",
    triangular_pair: "BTC_USDT FARM_BTC FARM_USDT",
  },
  {
    a_base: "BTC",
    b_base: "TRU",
    c_base: "TRU",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "BTC",
    pair_a: "BTC_USDT",
    pair_b: "TRU_USDT",
    pair_c: "TRU_BTC",
    triangular_pair: "BTC_USDT TRU_BTC TRU_USDT",
  },
  {
    a_base: "BTC",
    b_base: "TUSD",
    c_base: "BTC",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TUSD",
    pair_a: "BTC_USDT",
    pair_b: "TUSD_USDT",
    pair_c: "BTC_TUSD",
    triangular_pair: "BTC_TUSD BTC_USDT TUSD_USDT",
  },
  {
    a_base: "BTC",
    b_base: "SRM",
    c_base: "SRM",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "BTC",
    pair_a: "BTC_USDT",
    pair_b: "SRM_USDT",
    pair_c: "SRM_BTC",
    triangular_pair: "BTC_USDT SRM_BTC SRM_USDT",
  },
  {
    a_base: "BTC",
    b_base: "FIL",
    c_base: "FIL",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "FIL_BTC",
    pair_c: "FIL_USDT",
    triangular_pair: "BTC_USDT FIL_BTC FIL_USDT",
  },
  {
    a_base: "BTC",
    b_base: "XYM",
    c_base: "XYM",
    a_quote: "USDT",
    b_quote: "BTC",
    c_quote: "USDT",
    pair_a: "BTC_USDT",
    pair_b: "XYM_BTC",
    pair_c: "XYM_USDT",
    triangular_pair: "BTC_USDT XYM_BTC XYM_USDT",
  },
  {
    a_base: "BTC",
    b_base: "KLV",
    c_base: "KLV",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "BTC",
    pair_a: "BTC_USDT",
    pair_b: "KLV_USDT",
    pair_c: "KLV_BTC",
    triangular_pair: "BTC_USDT KLV_BTC KLV_USDT",
  },
  {
    a_base: "BTC",
    b_base: "AVAX",
    c_base: "AVAX",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "BTC",
    pair_a: "BTC_USDT",
    pair_b: "AVAX_USDT",
    pair_c: "AVAX_BTC",
    triangular_pair: "AVAX_BTC AVAX_USDT BTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "SOL",
    c_base: "SOL",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "BTC",
    pair_a: "BTC_USDT",
    pair_b: "SOL_USDT",
    pair_c: "SOL_BTC",
    triangular_pair: "BTC_USDT SOL_BTC SOL_USDT",
  },
  {
    a_base: "BTC",
    b_base: "FTM",
    c_base: "FTM",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "BTC",
    pair_a: "BTC_USDT",
    pair_b: "FTM_USDT",
    pair_c: "FTM_BTC",
    triangular_pair: "BTC_USDT FTM_BTC FTM_USDT",
  },
  {
    a_base: "BTC",
    b_base: "ADA",
    c_base: "ADA",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "BTC",
    pair_a: "BTC_USDT",
    pair_b: "ADA_USDT",
    pair_c: "ADA_BTC",
    triangular_pair: "ADA_BTC ADA_USDT BTC_USDT",
  },
  {
    a_base: "BTC",
    b_base: "USDD",
    c_base: "BTC",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "BTC_USDT",
    pair_b: "USDD_USDT",
    pair_c: "BTC_USDD",
    triangular_pair: "BTC_USDD BTC_USDT USDD_USDT",
  },
  {
    a_base: "DASH",
    b_base: "USDT",
    c_base: "DASH",
    a_quote: "USDT",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "DASH_USDT",
    pair_b: "USDT_USDC",
    pair_c: "DASH_USDC",
    triangular_pair: "DASH_USDC DASH_USDT USDT_USDC",
  },
  {
    a_base: "LTC",
    b_base: "USDT",
    c_base: "LTC",
    a_quote: "USDT",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "LTC_USDT",
    pair_b: "USDT_USDC",
    pair_c: "LTC_USDC",
    triangular_pair: "LTC_USDC LTC_USDT USDT_USDC",
  },
  {
    a_base: "LTC",
    b_base: "USDD",
    c_base: "LTC",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "LTC_USDT",
    pair_b: "USDD_USDT",
    pair_c: "LTC_USDD",
    triangular_pair: "LTC_USDD LTC_USDT USDD_USDT",
  },
  {
    a_base: "XLM",
    b_base: "USDT",
    c_base: "XLM",
    a_quote: "USDT",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "XLM_USDT",
    pair_b: "USDT_USDC",
    pair_c: "XLM_USDC",
    triangular_pair: "USDT_USDC XLM_USDC XLM_USDT",
  },
  {
    a_base: "XMR",
    b_base: "USDT",
    c_base: "XMR",
    a_quote: "USDT",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "XMR_USDT",
    pair_b: "USDT_USDC",
    pair_c: "XMR_USDC",
    triangular_pair: "USDT_USDC XMR_USDC XMR_USDT",
  },
  {
    a_base: "XRP",
    b_base: "USDT",
    c_base: "XRP",
    a_quote: "USDT",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "XRP_USDT",
    pair_b: "USDT_USDC",
    pair_c: "XRP_USDC",
    triangular_pair: "USDT_USDC XRP_USDC XRP_USDT",
  },
  {
    a_base: "XRP",
    b_base: "TRX",
    c_base: "XRP",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "XRP_USDT",
    pair_b: "TRX_USDT",
    pair_c: "XRP_TRX",
    triangular_pair: "TRX_USDT XRP_TRX XRP_USDT",
  },
  {
    a_base: "XRP",
    b_base: "USDD",
    c_base: "XRP",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "XRP_USDT",
    pair_b: "USDD_USDT",
    pair_c: "XRP_USDD",
    triangular_pair: "USDD_USDT XRP_USDD XRP_USDT",
  },
  {
    a_base: "ETH",
    b_base: "ETC",
    c_base: "ETC",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "ETH",
    pair_a: "ETH_BTC",
    pair_b: "ETC_BTC",
    pair_c: "ETC_ETH",
    triangular_pair: "ETC_BTC ETC_ETH ETH_BTC",
  },
  {
    a_base: "ETH",
    b_base: "ZEC",
    c_base: "ZEC",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "ETH",
    pair_a: "ETH_BTC",
    pair_b: "ZEC_BTC",
    pair_c: "ZEC_ETH",
    triangular_pair: "ETH_BTC ZEC_BTC ZEC_ETH",
  },
  {
    a_base: "ETH",
    b_base: "ZRX",
    c_base: "ZRX",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "ETH",
    pair_a: "ETH_BTC",
    pair_b: "ZRX_BTC",
    pair_c: "ZRX_ETH",
    triangular_pair: "ETH_BTC ZRX_BTC ZRX_ETH",
  },
  {
    a_base: "ETH",
    b_base: "EOS",
    c_base: "EOS",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "ETH",
    pair_a: "ETH_BTC",
    pair_b: "EOS_BTC",
    pair_c: "EOS_ETH",
    triangular_pair: "EOS_BTC EOS_ETH ETH_BTC",
  },
  {
    a_base: "ETH",
    b_base: "BTC",
    c_base: "ETH",
    a_quote: "BTC",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "ETH_BTC",
    pair_b: "BTC_USDC",
    pair_c: "ETH_USDC",
    triangular_pair: "BTC_USDC ETH_BTC ETH_USDC",
  },
  {
    a_base: "ETH",
    b_base: "TRX",
    c_base: "ETH",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "ETH_BTC",
    pair_b: "TRX_BTC",
    pair_c: "ETH_TRX",
    triangular_pair: "ETH_BTC ETH_TRX TRX_BTC",
  },
  {
    a_base: "ETH",
    b_base: "BTC",
    c_base: "ETH",
    a_quote: "BTC",
    b_quote: "TUSD",
    c_quote: "TUSD",
    pair_a: "ETH_BTC",
    pair_b: "BTC_TUSD",
    pair_c: "ETH_TUSD",
    triangular_pair: "BTC_TUSD ETH_BTC ETH_TUSD",
  },
  {
    a_base: "ETH",
    b_base: "BTC",
    c_base: "ETH",
    a_quote: "BTC",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "ETH_BTC",
    pair_b: "BTC_USDD",
    pair_c: "ETH_USDD",
    triangular_pair: "BTC_USDD ETH_BTC ETH_USDD",
  },
  {
    a_base: "ETH",
    b_base: "ETC",
    c_base: "ETC",
    a_quote: "USDT",
    b_quote: "ETH",
    c_quote: "USDT",
    pair_a: "ETH_USDT",
    pair_b: "ETC_ETH",
    pair_c: "ETC_USDT",
    triangular_pair: "ETC_ETH ETC_USDT ETH_USDT",
  },
  {
    a_base: "ETH",
    b_base: "ZEC",
    c_base: "ZEC",
    a_quote: "USDT",
    b_quote: "ETH",
    c_quote: "USDT",
    pair_a: "ETH_USDT",
    pair_b: "ZEC_ETH",
    pair_c: "ZEC_USDT",
    triangular_pair: "ETH_USDT ZEC_ETH ZEC_USDT",
  },
  {
    a_base: "ETH",
    b_base: "ZRX",
    c_base: "ZRX",
    a_quote: "USDT",
    b_quote: "ETH",
    c_quote: "USDT",
    pair_a: "ETH_USDT",
    pair_b: "ZRX_ETH",
    pair_c: "ZRX_USDT",
    triangular_pair: "ETH_USDT ZRX_ETH ZRX_USDT",
  },
  {
    a_base: "ETH",
    b_base: "EOS",
    c_base: "EOS",
    a_quote: "USDT",
    b_quote: "ETH",
    c_quote: "USDT",
    pair_a: "ETH_USDT",
    pair_b: "EOS_ETH",
    pair_c: "EOS_USDT",
    triangular_pair: "EOS_ETH EOS_USDT ETH_USDT",
  },
  {
    a_base: "ETH",
    b_base: "ETH",
    c_base: "USDT",
    a_quote: "USDT",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "ETH_USDT",
    pair_b: "ETH_USDC",
    pair_c: "USDT_USDC",
    triangular_pair: "ETH_USDC ETH_USDT USDT_USDC",
  },
  {
    a_base: "ETH",
    b_base: "TRX",
    c_base: "ETH",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "ETH_USDT",
    pair_b: "TRX_USDT",
    pair_c: "ETH_TRX",
    triangular_pair: "ETH_TRX ETH_USDT TRX_USDT",
  },
  {
    a_base: "ETH",
    b_base: "COMP",
    c_base: "COMP",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "ETH",
    pair_a: "ETH_USDT",
    pair_b: "COMP_USDT",
    pair_c: "COMP_ETH",
    triangular_pair: "COMP_ETH COMP_USDT ETH_USDT",
  },
  {
    a_base: "ETH",
    b_base: "TUSD",
    c_base: "ETH",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TUSD",
    pair_a: "ETH_USDT",
    pair_b: "TUSD_USDT",
    pair_c: "ETH_TUSD",
    triangular_pair: "ETH_TUSD ETH_USDT TUSD_USDT",
  },
  {
    a_base: "ETH",
    b_base: "USDD",
    c_base: "ETH",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "ETH_USDT",
    pair_b: "USDD_USDT",
    pair_c: "ETH_USDD",
    triangular_pair: "ETH_USDD ETH_USDT USDD_USDT",
  },
  {
    a_base: "ETH",
    b_base: "ETHW",
    c_base: "ETHW",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "ETH",
    pair_a: "ETH_USDT",
    pair_b: "ETHW_USDT",
    pair_c: "ETHW_ETH",
    triangular_pair: "ETHW_ETH ETHW_USDT ETH_USDT",
  },
  {
    a_base: "STEEM",
    b_base: "TRX",
    c_base: "STEEM",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "STEEM_BTC",
    pair_b: "TRX_BTC",
    pair_c: "STEEM_TRX",
    triangular_pair: "STEEM_BTC STEEM_TRX TRX_BTC",
  },
  {
    a_base: "ETC",
    b_base: "BTC",
    c_base: "ETC",
    a_quote: "BTC",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "ETC_BTC",
    pair_b: "BTC_USDC",
    pair_c: "ETC_USDC",
    triangular_pair: "BTC_USDC ETC_BTC ETC_USDC",
  },
  {
    a_base: "ETC",
    b_base: "ETH",
    c_base: "ETC",
    a_quote: "ETH",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "ETC_ETH",
    pair_b: "ETH_USDC",
    pair_c: "ETC_USDC",
    triangular_pair: "ETC_ETH ETC_USDC ETH_USDC",
  },
  {
    a_base: "ETC",
    b_base: "USDT",
    c_base: "ETC",
    a_quote: "USDT",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "ETC_USDT",
    pair_b: "USDT_USDC",
    pair_c: "ETC_USDC",
    triangular_pair: "ETC_USDC ETC_USDT USDT_USDC",
  },
  {
    a_base: "ZEC",
    b_base: "BTC",
    c_base: "ZEC",
    a_quote: "BTC",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "ZEC_BTC",
    pair_b: "BTC_USDC",
    pair_c: "ZEC_USDC",
    triangular_pair: "BTC_USDC ZEC_BTC ZEC_USDC",
  },
  {
    a_base: "ZEC",
    b_base: "ETH",
    c_base: "ZEC",
    a_quote: "ETH",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "ZEC_ETH",
    pair_b: "ETH_USDC",
    pair_c: "ZEC_USDC",
    triangular_pair: "ETH_USDC ZEC_ETH ZEC_USDC",
  },
  {
    a_base: "ZEC",
    b_base: "USDT",
    c_base: "ZEC",
    a_quote: "USDT",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "ZEC_USDT",
    pair_b: "USDT_USDC",
    pair_c: "ZEC_USDC",
    triangular_pair: "USDT_USDC ZEC_USDC ZEC_USDT",
  },
  {
    a_base: "EOS",
    b_base: "BTC",
    c_base: "EOS",
    a_quote: "BTC",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "EOS_BTC",
    pair_b: "BTC_USDC",
    pair_c: "EOS_USDC",
    triangular_pair: "BTC_USDC EOS_BTC EOS_USDC",
  },
  {
    a_base: "EOS",
    b_base: "ETH",
    c_base: "EOS",
    a_quote: "ETH",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "EOS_ETH",
    pair_b: "ETH_USDC",
    pair_c: "EOS_USDC",
    triangular_pair: "EOS_ETH EOS_USDC ETH_USDC",
  },
  {
    a_base: "EOS",
    b_base: "USDT",
    c_base: "EOS",
    a_quote: "USDT",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "EOS_USDT",
    pair_b: "USDT_USDC",
    pair_c: "EOS_USDC",
    triangular_pair: "EOS_USDC EOS_USDT USDT_USDC",
  },
  {
    a_base: "DOGE",
    b_base: "USDT",
    c_base: "DOGE",
    a_quote: "USDT",
    b_quote: "USDC",
    c_quote: "USDC",
    pair_a: "DOGE_USDT",
    pair_b: "USDT_USDC",
    pair_c: "DOGE_USDC",
    triangular_pair: "DOGE_USDC DOGE_USDT USDT_USDC",
  },
  {
    a_base: "DOGE",
    b_base: "USDD",
    c_base: "DOGE",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "DOGE_USDT",
    pair_b: "USDD_USDT",
    pair_c: "DOGE_USDD",
    triangular_pair: "DOGE_USDD DOGE_USDT USDD_USDT",
  },
  {
    a_base: "BTC",
    b_base: "MANA",
    c_base: "MANA",
    a_quote: "USDC",
    b_quote: "BTC",
    c_quote: "USDC",
    pair_a: "BTC_USDC",
    pair_b: "MANA_BTC",
    pair_c: "MANA_USDC",
    triangular_pair: "BTC_USDC MANA_BTC MANA_USDC",
  },
  {
    a_base: "BTC",
    b_base: "BCHSV",
    c_base: "BCHSV",
    a_quote: "USDC",
    b_quote: "BTC",
    c_quote: "USDC",
    pair_a: "BTC_USDC",
    pair_b: "BCHSV_BTC",
    pair_c: "BCHSV_USDC",
    triangular_pair: "BCHSV_BTC BCHSV_USDC BTC_USDC",
  },
  {
    a_base: "BTC",
    b_base: "ATOM",
    c_base: "ATOM",
    a_quote: "USDC",
    b_quote: "BTC",
    c_quote: "USDC",
    pair_a: "BTC_USDC",
    pair_b: "ATOM_BTC",
    pair_c: "ATOM_USDC",
    triangular_pair: "ATOM_BTC ATOM_USDC BTC_USDC",
  },
  {
    a_base: "BTC",
    b_base: "TRX",
    c_base: "TRX",
    a_quote: "USDC",
    b_quote: "BTC",
    c_quote: "USDC",
    pair_a: "BTC_USDC",
    pair_b: "TRX_BTC",
    pair_c: "TRX_USDC",
    triangular_pair: "BTC_USDC TRX_BTC TRX_USDC",
  },
  {
    a_base: "BTC",
    b_base: "LINK",
    c_base: "LINK",
    a_quote: "USDC",
    b_quote: "BTC",
    c_quote: "USDC",
    pair_a: "BTC_USDC",
    pair_b: "LINK_BTC",
    pair_c: "LINK_USDC",
    triangular_pair: "BTC_USDC LINK_BTC LINK_USDC",
  },
  {
    a_base: "BTC",
    b_base: "MATIC",
    c_base: "MATIC",
    a_quote: "USDC",
    b_quote: "BTC",
    c_quote: "USDC",
    pair_a: "BTC_USDC",
    pair_b: "MATIC_BTC",
    pair_c: "MATIC_USDC",
    triangular_pair: "BTC_USDC MATIC_BTC MATIC_USDC",
  },
  {
    a_base: "BTC",
    b_base: "BTC",
    c_base: "BNB",
    a_quote: "USDC",
    b_quote: "BNB",
    c_quote: "USDC",
    pair_a: "BTC_USDC",
    pair_b: "BTC_BNB",
    pair_c: "BNB_USDC",
    triangular_pair: "BNB_USDC BTC_BNB BTC_USDC",
  },
  {
    a_base: "BTC",
    b_base: "BCH",
    c_base: "BCH",
    a_quote: "USDC",
    b_quote: "BTC",
    c_quote: "USDC",
    pair_a: "BTC_USDC",
    pair_b: "BCH_BTC",
    pair_c: "BCH_USDC",
    triangular_pair: "BCH_BTC BCH_USDC BTC_USDC",
  },
  {
    a_base: "BTC",
    b_base: "TUSD",
    c_base: "BTC",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "TUSD",
    pair_a: "BTC_USDC",
    pair_b: "TUSD_USDC",
    pair_c: "BTC_TUSD",
    triangular_pair: "BTC_TUSD BTC_USDC TUSD_USDC",
  },
  {
    a_base: "BTC",
    b_base: "SRM",
    c_base: "SRM",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "BTC",
    pair_a: "BTC_USDC",
    pair_b: "SRM_USDC",
    pair_c: "SRM_BTC",
    triangular_pair: "BTC_USDC SRM_BTC SRM_USDC",
  },
  {
    a_base: "BTC",
    b_base: "AVAX",
    c_base: "AVAX",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "BTC",
    pair_a: "BTC_USDC",
    pair_b: "AVAX_USDC",
    pair_c: "AVAX_BTC",
    triangular_pair: "AVAX_BTC AVAX_USDC BTC_USDC",
  },
  {
    a_base: "BTC",
    b_base: "SOL",
    c_base: "SOL",
    a_quote: "USDC",
    b_quote: "BTC",
    c_quote: "USDC",
    pair_a: "BTC_USDC",
    pair_b: "SOL_BTC",
    pair_c: "SOL_USDC",
    triangular_pair: "BTC_USDC SOL_BTC SOL_USDC",
  },
  {
    a_base: "BTC",
    b_base: "ADA",
    c_base: "ADA",
    a_quote: "USDC",
    b_quote: "BTC",
    c_quote: "USDC",
    pair_a: "BTC_USDC",
    pair_b: "ADA_BTC",
    pair_c: "ADA_USDC",
    triangular_pair: "ADA_BTC ADA_USDC BTC_USDC",
  },
  {
    a_base: "BTC",
    b_base: "FTM",
    c_base: "FTM",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "BTC",
    pair_a: "BTC_USDC",
    pair_b: "FTM_USDC",
    pair_c: "FTM_BTC",
    triangular_pair: "BTC_USDC FTM_BTC FTM_USDC",
  },
  {
    a_base: "BTC",
    b_base: "USDD",
    c_base: "BTC",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "USDD",
    pair_a: "BTC_USDC",
    pair_b: "USDD_USDC",
    pair_c: "BTC_USDD",
    triangular_pair: "BTC_USDC BTC_USDD USDD_USDC",
  },
  {
    a_base: "ETH",
    b_base: "TRX",
    c_base: "ETH",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "TRX",
    pair_a: "ETH_USDC",
    pair_b: "TRX_USDC",
    pair_c: "ETH_TRX",
    triangular_pair: "ETH_TRX ETH_USDC TRX_USDC",
  },
  {
    a_base: "ETH",
    b_base: "TUSD",
    c_base: "ETH",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "TUSD",
    pair_a: "ETH_USDC",
    pair_b: "TUSD_USDC",
    pair_c: "ETH_TUSD",
    triangular_pair: "ETH_TUSD ETH_USDC TUSD_USDC",
  },
  {
    a_base: "ETH",
    b_base: "USDD",
    c_base: "ETH",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "USDD",
    pair_a: "ETH_USDC",
    pair_b: "USDD_USDC",
    pair_c: "ETH_USDD",
    triangular_pair: "ETH_USDC ETH_USDD USDD_USDC",
  },
  {
    a_base: "USDT",
    b_base: "MANA",
    c_base: "MANA",
    a_quote: "USDC",
    b_quote: "USDT",
    c_quote: "USDC",
    pair_a: "USDT_USDC",
    pair_b: "MANA_USDT",
    pair_c: "MANA_USDC",
    triangular_pair: "MANA_USDC MANA_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "BCHSV",
    c_base: "BCHSV",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "USDT",
    pair_a: "USDT_USDC",
    pair_b: "BCHSV_USDC",
    pair_c: "BCHSV_USDT",
    triangular_pair: "BCHSV_USDC BCHSV_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "ATOM",
    c_base: "ATOM",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "USDT",
    pair_a: "USDT_USDC",
    pair_b: "ATOM_USDC",
    pair_c: "ATOM_USDT",
    triangular_pair: "ATOM_USDC ATOM_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "TRX",
    c_base: "TRX",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "USDT",
    pair_a: "USDT_USDC",
    pair_b: "TRX_USDC",
    pair_c: "TRX_USDT",
    triangular_pair: "TRX_USDC TRX_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "BTT",
    c_base: "BTT",
    a_quote: "USDC",
    b_quote: "USDT",
    c_quote: "USDC",
    pair_a: "USDT_USDC",
    pair_b: "BTT_USDT",
    pair_c: "BTT_USDC",
    triangular_pair: "BTT_USDC BTT_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "MATIC",
    c_base: "MATIC",
    a_quote: "USDC",
    b_quote: "USDT",
    c_quote: "USDC",
    pair_a: "USDT_USDC",
    pair_b: "MATIC_USDT",
    pair_c: "MATIC_USDC",
    triangular_pair: "MATIC_USDC MATIC_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "LINK",
    c_base: "LINK",
    a_quote: "USDC",
    b_quote: "USDT",
    c_quote: "USDC",
    pair_a: "USDT_USDC",
    pair_b: "LINK_USDT",
    pair_c: "LINK_USDC",
    triangular_pair: "LINK_USDC LINK_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "BNB",
    c_base: "BNB",
    a_quote: "USDC",
    b_quote: "USDT",
    c_quote: "USDC",
    pair_a: "USDT_USDC",
    pair_b: "BNB_USDT",
    pair_c: "BNB_USDC",
    triangular_pair: "BNB_USDC BNB_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "BCH",
    c_base: "BCH",
    a_quote: "USDC",
    b_quote: "USDT",
    c_quote: "USDC",
    pair_a: "USDT_USDC",
    pair_b: "BCH_USDT",
    pair_c: "BCH_USDC",
    triangular_pair: "BCH_USDC BCH_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "TUSD",
    c_base: "TUSD",
    a_quote: "USDC",
    b_quote: "USDT",
    c_quote: "USDC",
    pair_a: "USDT_USDC",
    pair_b: "TUSD_USDT",
    pair_c: "TUSD_USDC",
    triangular_pair: "TUSD_USDC TUSD_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "SRM",
    c_base: "SRM",
    a_quote: "USDC",
    b_quote: "USDT",
    c_quote: "USDC",
    pair_a: "USDT_USDC",
    pair_b: "SRM_USDT",
    pair_c: "SRM_USDC",
    triangular_pair: "SRM_USDC SRM_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "SHIB",
    c_base: "SHIB",
    a_quote: "USDC",
    b_quote: "USDT",
    c_quote: "USDC",
    pair_a: "USDT_USDC",
    pair_b: "SHIB_USDT",
    pair_c: "SHIB_USDC",
    triangular_pair: "SHIB_USDC SHIB_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "XEM",
    c_base: "XEM",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "USDT",
    pair_a: "USDT_USDC",
    pair_b: "XEM_USDC",
    pair_c: "XEM_USDT",
    triangular_pair: "USDT_USDC XEM_USDC XEM_USDT",
  },
  {
    a_base: "USDT",
    b_base: "AVAX",
    c_base: "AVAX",
    a_quote: "USDC",
    b_quote: "USDT",
    c_quote: "USDC",
    pair_a: "USDT_USDC",
    pair_b: "AVAX_USDT",
    pair_c: "AVAX_USDC",
    triangular_pair: "AVAX_USDC AVAX_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "SOL",
    c_base: "SOL",
    a_quote: "USDC",
    b_quote: "USDT",
    c_quote: "USDC",
    pair_a: "USDT_USDC",
    pair_b: "SOL_USDT",
    pair_c: "SOL_USDC",
    triangular_pair: "SOL_USDC SOL_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "FTM",
    c_base: "FTM",
    a_quote: "USDC",
    b_quote: "USDT",
    c_quote: "USDC",
    pair_a: "USDT_USDC",
    pair_b: "FTM_USDT",
    pair_c: "FTM_USDC",
    triangular_pair: "FTM_USDC FTM_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "ADA",
    c_base: "ADA",
    a_quote: "USDC",
    b_quote: "USDT",
    c_quote: "USDC",
    pair_a: "USDT_USDC",
    pair_b: "ADA_USDT",
    pair_c: "ADA_USDC",
    triangular_pair: "ADA_USDC ADA_USDT USDT_USDC",
  },
  {
    a_base: "USDT",
    b_base: "USDD",
    c_base: "USDD",
    a_quote: "USDC",
    b_quote: "USDT",
    c_quote: "USDC",
    pair_a: "USDT_USDC",
    pair_b: "USDD_USDT",
    pair_c: "USDD_USDC",
    triangular_pair: "USDD_USDC USDD_USDT USDT_USDC",
  },
  {
    a_base: "XRP",
    b_base: "TRX",
    c_base: "XRP",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "TRX",
    pair_a: "XRP_USDC",
    pair_b: "TRX_USDC",
    pair_c: "XRP_TRX",
    triangular_pair: "TRX_USDC XRP_TRX XRP_USDC",
  },
  {
    a_base: "XRP",
    b_base: "USDD",
    c_base: "XRP",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "USDD",
    pair_a: "XRP_USDC",
    pair_b: "USDD_USDC",
    pair_c: "XRP_USDD",
    triangular_pair: "USDD_USDC XRP_USDC XRP_USDD",
  },
  {
    a_base: "DOGE",
    b_base: "USDD",
    c_base: "DOGE",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "USDD",
    pair_a: "DOGE_USDC",
    pair_b: "USDD_USDC",
    pair_c: "DOGE_USDD",
    triangular_pair: "DOGE_USDC DOGE_USDD USDD_USDC",
  },
  {
    a_base: "LTC",
    b_base: "USDD",
    c_base: "LTC",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "USDD",
    pair_a: "LTC_USDC",
    pair_b: "USDD_USDC",
    pair_c: "LTC_USDD",
    triangular_pair: "LTC_USDC LTC_USDD USDD_USDC",
  },
  {
    a_base: "TRX",
    b_base: "LINK",
    c_base: "LINK",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "LINK_BTC",
    pair_c: "LINK_TRX",
    triangular_pair: "LINK_BTC LINK_TRX TRX_BTC",
  },
  {
    a_base: "TRX",
    b_base: "XTZ",
    c_base: "XTZ",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "XTZ_BTC",
    pair_c: "XTZ_TRX",
    triangular_pair: "TRX_BTC XTZ_BTC XTZ_TRX",
  },
  {
    a_base: "TRX",
    b_base: "SNX",
    c_base: "SNX",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "SNX_BTC",
    pair_c: "SNX_TRX",
    triangular_pair: "SNX_BTC SNX_TRX TRX_BTC",
  },
  {
    a_base: "TRX",
    b_base: "MATIC",
    c_base: "MATIC",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "MATIC_BTC",
    pair_c: "MATIC_TRX",
    triangular_pair: "MATIC_BTC MATIC_TRX TRX_BTC",
  },
  {
    a_base: "TRX",
    b_base: "NEO",
    c_base: "NEO",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "NEO_BTC",
    pair_c: "NEO_TRX",
    triangular_pair: "NEO_BTC NEO_TRX TRX_BTC",
  },
  {
    a_base: "TRX",
    b_base: "SWFTC",
    c_base: "SWFTC",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "SWFTC_BTC",
    pair_c: "SWFTC_TRX",
    triangular_pair: "SWFTC_BTC SWFTC_TRX TRX_BTC",
  },
  {
    a_base: "TRX",
    b_base: "AVA",
    c_base: "AVA",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "AVA_BTC",
    pair_c: "AVA_TRX",
    triangular_pair: "AVA_BTC AVA_TRX TRX_BTC",
  },
  {
    a_base: "TRX",
    b_base: "CHR",
    c_base: "CHR",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "CHR_BTC",
    pair_c: "CHR_TRX",
    triangular_pair: "CHR_BTC CHR_TRX TRX_BTC",
  },
  {
    a_base: "TRX",
    b_base: "BTC",
    c_base: "BNB",
    a_quote: "BTC",
    b_quote: "BNB",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "BTC_BNB",
    pair_c: "BNB_TRX",
    triangular_pair: "BNB_TRX BTC_BNB TRX_BTC",
  },
  {
    a_base: "TRX",
    b_base: "MDT",
    c_base: "MDT",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "MDT_BTC",
    pair_c: "MDT_TRX",
    triangular_pair: "MDT_BTC MDT_TRX TRX_BTC",
  },
  {
    a_base: "TRX",
    b_base: "WRX",
    c_base: "WRX",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "WRX_BTC",
    pair_c: "WRX_TRX",
    triangular_pair: "TRX_BTC WRX_BTC WRX_TRX",
  },
  {
    a_base: "TRX",
    b_base: "SXP",
    c_base: "SXP",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "SXP_BTC",
    pair_c: "SXP_TRX",
    triangular_pair: "SXP_BTC SXP_TRX TRX_BTC",
  },
  {
    a_base: "TRX",
    b_base: "SWINGBY",
    c_base: "SWINGBY",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "SWINGBY_BTC",
    pair_c: "SWINGBY_TRX",
    triangular_pair: "SWINGBY_BTC SWINGBY_TRX TRX_BTC",
  },
  {
    a_base: "TRX",
    b_base: "FUND",
    c_base: "FUND",
    a_quote: "BTC",
    b_quote: "TRX",
    c_quote: "BTC",
    pair_a: "TRX_BTC",
    pair_b: "FUND_TRX",
    pair_c: "FUND_BTC",
    triangular_pair: "FUND_BTC FUND_TRX TRX_BTC",
  },
  {
    a_base: "TRX",
    b_base: "AMP",
    c_base: "AMP",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "AMP_BTC",
    pair_c: "AMP_TRX",
    triangular_pair: "AMP_BTC AMP_TRX TRX_BTC",
  },
  {
    a_base: "TRX",
    b_base: "KLV",
    c_base: "KLV",
    a_quote: "BTC",
    b_quote: "BTC",
    c_quote: "TRX",
    pair_a: "TRX_BTC",
    pair_b: "KLV_BTC",
    pair_c: "KLV_TRX",
    triangular_pair: "KLV_BTC KLV_TRX TRX_BTC",
  },
  {
    a_base: "TRX",
    b_base: "BTC",
    c_base: "TRX",
    a_quote: "BTC",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "TRX_BTC",
    pair_b: "BTC_USDD",
    pair_c: "TRX_USDD",
    triangular_pair: "BTC_USDD TRX_BTC TRX_USDD",
  },
  {
    a_base: "TRX",
    b_base: "BTT",
    c_base: "BTT",
    a_quote: "USDC",
    b_quote: "TRX",
    c_quote: "USDC",
    pair_a: "TRX_USDC",
    pair_b: "BTT_TRX",
    pair_c: "BTT_USDC",
    triangular_pair: "BTT_TRX BTT_USDC TRX_USDC",
  },
  {
    a_base: "TRX",
    b_base: "LINK",
    c_base: "LINK",
    a_quote: "USDC",
    b_quote: "TRX",
    c_quote: "USDC",
    pair_a: "TRX_USDC",
    pair_b: "LINK_TRX",
    pair_c: "LINK_USDC",
    triangular_pair: "LINK_TRX LINK_USDC TRX_USDC",
  },
  {
    a_base: "TRX",
    b_base: "MATIC",
    c_base: "MATIC",
    a_quote: "USDC",
    b_quote: "TRX",
    c_quote: "USDC",
    pair_a: "TRX_USDC",
    pair_b: "MATIC_TRX",
    pair_c: "MATIC_USDC",
    triangular_pair: "MATIC_TRX MATIC_USDC TRX_USDC",
  },
  {
    a_base: "TRX",
    b_base: "BNB",
    c_base: "BNB",
    a_quote: "USDC",
    b_quote: "TRX",
    c_quote: "USDC",
    pair_a: "TRX_USDC",
    pair_b: "BNB_TRX",
    pair_c: "BNB_USDC",
    triangular_pair: "BNB_TRX BNB_USDC TRX_USDC",
  },
  {
    a_base: "TRX",
    b_base: "USDD",
    c_base: "TRX",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "USDD",
    pair_a: "TRX_USDC",
    pair_b: "USDD_USDC",
    pair_c: "TRX_USDD",
    triangular_pair: "TRX_USDC TRX_USDD USDD_USDC",
  },
  {
    a_base: "TRX",
    b_base: "BTT",
    c_base: "BTT",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "BTT_USDT",
    pair_c: "BTT_TRX",
    triangular_pair: "BTT_TRX BTT_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "WIN",
    c_base: "WIN",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "WIN_USDT",
    pair_c: "WIN_TRX",
    triangular_pair: "TRX_USDT WIN_TRX WIN_USDT",
  },
  {
    a_base: "TRX",
    b_base: "STEEM",
    c_base: "STEEM",
    a_quote: "USDT",
    b_quote: "TRX",
    c_quote: "USDT",
    pair_a: "TRX_USDT",
    pair_b: "STEEM_TRX",
    pair_c: "STEEM_USDT",
    triangular_pair: "STEEM_TRX STEEM_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "LINK",
    c_base: "LINK",
    a_quote: "USDT",
    b_quote: "TRX",
    c_quote: "USDT",
    pair_a: "TRX_USDT",
    pair_b: "LINK_TRX",
    pair_c: "LINK_USDT",
    triangular_pair: "LINK_TRX LINK_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "XTZ",
    c_base: "XTZ",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "XTZ_USDT",
    pair_c: "XTZ_TRX",
    triangular_pair: "TRX_USDT XTZ_TRX XTZ_USDT",
  },
  {
    a_base: "TRX",
    b_base: "SNX",
    c_base: "SNX",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "SNX_USDT",
    pair_c: "SNX_TRX",
    triangular_pair: "SNX_TRX SNX_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "MATIC",
    c_base: "MATIC",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "MATIC_USDT",
    pair_c: "MATIC_TRX",
    triangular_pair: "MATIC_TRX MATIC_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "NEO",
    c_base: "NEO",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "NEO_USDT",
    pair_c: "NEO_TRX",
    triangular_pair: "NEO_TRX NEO_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "SWFTC",
    c_base: "SWFTC",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "SWFTC_USDT",
    pair_c: "SWFTC_TRX",
    triangular_pair: "SWFTC_TRX SWFTC_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "JST",
    c_base: "JST",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "JST_USDT",
    pair_c: "JST_TRX",
    triangular_pair: "JST_TRX JST_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "AVA",
    c_base: "AVA",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "AVA_USDT",
    pair_c: "AVA_TRX",
    triangular_pair: "AVA_TRX AVA_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "CHR",
    c_base: "CHR",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "CHR_USDT",
    pair_c: "CHR_TRX",
    triangular_pair: "CHR_TRX CHR_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "BNB",
    c_base: "BNB",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "BNB_USDT",
    pair_c: "BNB_TRX",
    triangular_pair: "BNB_TRX BNB_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "MDT",
    c_base: "MDT",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "MDT_USDT",
    pair_c: "MDT_TRX",
    triangular_pair: "MDT_TRX MDT_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "WRX",
    c_base: "WRX",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "WRX_USDT",
    pair_c: "WRX_TRX",
    triangular_pair: "TRX_USDT WRX_TRX WRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "SXP",
    c_base: "SXP",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "SXP_USDT",
    pair_c: "SXP_TRX",
    triangular_pair: "SXP_TRX SXP_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "SWINGBY",
    c_base: "SWINGBY",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "SWINGBY_USDT",
    pair_c: "SWINGBY_TRX",
    triangular_pair: "SWINGBY_TRX SWINGBY_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "FUND",
    c_base: "FUND",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "FUND_USDT",
    pair_c: "FUND_TRX",
    triangular_pair: "FUND_TRX FUND_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "AMP",
    c_base: "AMP",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "AMP_USDT",
    pair_c: "AMP_TRX",
    triangular_pair: "AMP_TRX AMP_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "KLV",
    c_base: "KLV",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "KLV_USDT",
    pair_c: "KLV_TRX",
    triangular_pair: "KLV_TRX KLV_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "NFT",
    c_base: "NFT",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "NFT_USDT",
    pair_c: "NFT_TRX",
    triangular_pair: "NFT_TRX NFT_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "SUN",
    c_base: "SUN",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "SUN_USDT",
    pair_c: "SUN_TRX",
    triangular_pair: "SUN_TRX SUN_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "MATTER",
    c_base: "MATTER",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TRX",
    pair_a: "TRX_USDT",
    pair_b: "MATTER_USDT",
    pair_c: "MATTER_TRX",
    triangular_pair: "MATTER_TRX MATTER_USDT TRX_USDT",
  },
  {
    a_base: "TRX",
    b_base: "USDD",
    c_base: "TRX",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "TRX_USDT",
    pair_b: "USDD_USDT",
    pair_c: "TRX_USDD",
    triangular_pair: "TRX_USDD TRX_USDT USDD_USDT",
  },
  {
    a_base: "ETH",
    b_base: "ETH",
    c_base: "TRX",
    a_quote: "TRX",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "ETH_TRX",
    pair_b: "ETH_USDD",
    pair_c: "TRX_USDD",
    triangular_pair: "ETH_TRX ETH_USDD TRX_USDD",
  },
  {
    a_base: "XRP",
    b_base: "TRX",
    c_base: "XRP",
    a_quote: "TRX",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "XRP_TRX",
    pair_b: "TRX_USDD",
    pair_c: "XRP_USDD",
    triangular_pair: "TRX_USDD XRP_TRX XRP_USDD",
  },
  {
    a_base: "BTT",
    b_base: "USDD",
    c_base: "BTT",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "BTT_USDT",
    pair_b: "USDD_USDT",
    pair_c: "BTT_USDD",
    triangular_pair: "BTT_USDD BTT_USDT USDD_USDT",
  },
  {
    a_base: "BTT",
    b_base: "TRX",
    c_base: "BTT",
    a_quote: "TRX",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "BTT_TRX",
    pair_b: "TRX_USDD",
    pair_c: "BTT_USDD",
    triangular_pair: "BTT_TRX BTT_USDD TRX_USDD",
  },
  {
    a_base: "WIN",
    b_base: "USDD",
    c_base: "WIN",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "WIN_USDT",
    pair_b: "USDD_USDT",
    pair_c: "WIN_USDD",
    triangular_pair: "USDD_USDT WIN_USDD WIN_USDT",
  },
  {
    a_base: "WIN",
    b_base: "TRX",
    c_base: "WIN",
    a_quote: "TRX",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "WIN_TRX",
    pair_b: "TRX_USDD",
    pair_c: "WIN_USDD",
    triangular_pair: "TRX_USDD WIN_TRX WIN_USDD",
  },
  {
    a_base: "JST",
    b_base: "USDD",
    c_base: "JST",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "JST_USDT",
    pair_b: "USDD_USDT",
    pair_c: "JST_USDD",
    triangular_pair: "JST_USDD JST_USDT USDD_USDT",
  },
  {
    a_base: "JST",
    b_base: "TRX",
    c_base: "JST",
    a_quote: "TRX",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "JST_TRX",
    pair_b: "TRX_USDD",
    pair_c: "JST_USDD",
    triangular_pair: "JST_TRX JST_USDD TRX_USDD",
  },
  {
    a_base: "DOT",
    b_base: "USDD",
    c_base: "DOT",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "DOT_USDT",
    pair_b: "USDD_USDT",
    pair_c: "DOT_USDD",
    triangular_pair: "DOT_USDD DOT_USDT USDD_USDT",
  },
  {
    a_base: "DOT",
    b_base: "BTC",
    c_base: "DOT",
    a_quote: "BTC",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "DOT_BTC",
    pair_b: "BTC_USDD",
    pair_c: "DOT_USDD",
    triangular_pair: "BTC_USDD DOT_BTC DOT_USDD",
  },
  {
    a_base: "TRU",
    b_base: "TUSD",
    c_base: "TRU",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "TUSD",
    pair_a: "TRU_USDT",
    pair_b: "TUSD_USDT",
    pair_c: "TRU_TUSD",
    triangular_pair: "TRU_TUSD TRU_USDT TUSD_USDT",
  },
  {
    a_base: "TUSD",
    b_base: "USDD",
    c_base: "TUSD",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "TUSD_USDT",
    pair_b: "USDD_USDT",
    pair_c: "TUSD_USDD",
    triangular_pair: "TUSD_USDD TUSD_USDT USDD_USDT",
  },
  {
    a_base: "TUSD",
    b_base: "USDD",
    c_base: "TUSD",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "USDD",
    pair_a: "TUSD_USDC",
    pair_b: "USDD_USDC",
    pair_c: "TUSD_USDD",
    triangular_pair: "TUSD_USDC TUSD_USDD USDD_USDC",
  },
  {
    a_base: "TRU",
    b_base: "BTC",
    c_base: "TRU",
    a_quote: "BTC",
    b_quote: "TUSD",
    c_quote: "TUSD",
    pair_a: "TRU_BTC",
    pair_b: "BTC_TUSD",
    pair_c: "TRU_TUSD",
    triangular_pair: "BTC_TUSD TRU_BTC TRU_TUSD",
  },
  {
    a_base: "BTC",
    b_base: "BTC",
    c_base: "TUSD",
    a_quote: "TUSD",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "BTC_TUSD",
    pair_b: "BTC_USDD",
    pair_c: "TUSD_USDD",
    triangular_pair: "BTC_TUSD BTC_USDD TUSD_USDD",
  },
  {
    a_base: "ETH",
    b_base: "ETH",
    c_base: "TUSD",
    a_quote: "TUSD",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "ETH_TUSD",
    pair_b: "ETH_USDD",
    pair_c: "TUSD_USDD",
    triangular_pair: "ETH_TUSD ETH_USDD TUSD_USDD",
  },
  {
    a_base: "SHIB",
    b_base: "USDD",
    c_base: "SHIB",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "SHIB_USDT",
    pair_b: "USDD_USDT",
    pair_c: "SHIB_USDD",
    triangular_pair: "SHIB_USDD SHIB_USDT USDD_USDT",
  },
  {
    a_base: "ELON",
    b_base: "USDD",
    c_base: "ELON",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "ELON_USDT",
    pair_b: "USDD_USDT",
    pair_c: "ELON_USDD",
    triangular_pair: "ELON_USDD ELON_USDT USDD_USDT",
  },
  {
    a_base: "NFT",
    b_base: "USDD",
    c_base: "NFT",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "NFT_USDT",
    pair_b: "USDD_USDT",
    pair_c: "NFT_USDD",
    triangular_pair: "NFT_USDD NFT_USDT USDD_USDT",
  },
  {
    a_base: "NFT",
    b_base: "TRX",
    c_base: "NFT",
    a_quote: "TRX",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "NFT_TRX",
    pair_b: "TRX_USDD",
    pair_c: "NFT_USDD",
    triangular_pair: "NFT_TRX NFT_USDD TRX_USDD",
  },
  {
    a_base: "SUN",
    b_base: "USDD",
    c_base: "SUN",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "SUN_USDT",
    pair_b: "USDD_USDT",
    pair_c: "SUN_USDD",
    triangular_pair: "SUN_USDD SUN_USDT USDD_USDT",
  },
  {
    a_base: "SUN",
    b_base: "TRX",
    c_base: "SUN",
    a_quote: "TRX",
    b_quote: "USDD",
    c_quote: "USDD",
    pair_a: "SUN_TRX",
    pair_b: "TRX_USDD",
    pair_c: "SUN_USDD",
    triangular_pair: "SUN_TRX SUN_USDD TRX_USDD",
  },
  {
    a_base: "BTT",
    b_base: "USDD",
    c_base: "BTT",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "USDD",
    pair_a: "BTT_USDC",
    pair_b: "USDD_USDC",
    pair_c: "BTT_USDD",
    triangular_pair: "BTT_USDC BTT_USDD USDD_USDC",
  },
  {
    a_base: "CHZ",
    b_base: "USDD",
    c_base: "CHZ",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "CHZ_USDT",
    pair_b: "USDD_USDT",
    pair_c: "CHZ_USDD",
    triangular_pair: "CHZ_USDD CHZ_USDT USDD_USDT",
  },
  {
    a_base: "SHIB",
    b_base: "USDD",
    c_base: "SHIB",
    a_quote: "USDC",
    b_quote: "USDC",
    c_quote: "USDD",
    pair_a: "SHIB_USDC",
    pair_b: "USDD_USDC",
    pair_c: "SHIB_USDD",
    triangular_pair: "SHIB_USDC SHIB_USDD USDD_USDC",
  },
  {
    a_base: "KSM",
    b_base: "USDD",
    c_base: "KSM",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "KSM_USDT",
    pair_b: "USDD_USDT",
    pair_c: "KSM_USDD",
    triangular_pair: "KSM_USDD KSM_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "FRAX",
    c_base: "FRAX",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "USDD_USDT",
    pair_b: "FRAX_USDT",
    pair_c: "FRAX_USDD",
    triangular_pair: "FRAX_USDD FRAX_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "KUB",
    c_base: "KUB",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "USDD_USDT",
    pair_b: "KUB_USDT",
    pair_c: "KUB_USDD",
    triangular_pair: "KUB_USDD KUB_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "WLKN",
    c_base: "WLKN",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "USDD_USDT",
    pair_b: "WLKN_USDT",
    pair_c: "WLKN_USDD",
    triangular_pair: "USDD_USDT WLKN_USDD WLKN_USDT",
  },
  {
    a_base: "USDD",
    b_base: "LUNA",
    c_base: "LUNA",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "USDD_USDT",
    pair_b: "LUNA_USDT",
    pair_c: "LUNA_USDD",
    triangular_pair: "LUNA_USDD LUNA_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "LUNC",
    c_base: "LUNC",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "USDD_USDT",
    pair_b: "LUNC_USDT",
    pair_c: "LUNC_USDD",
    triangular_pair: "LUNC_USDD LUNC_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "ETHW",
    c_base: "ETHW",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "ETHW_USDD",
    pair_c: "ETHW_USDT",
    triangular_pair: "ETHW_USDD ETHW_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "SANTOS",
    c_base: "SANTOS",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "USDD_USDT",
    pair_b: "SANTOS_USDT",
    pair_c: "SANTOS_USDD",
    triangular_pair: "SANTOS_USDD SANTOS_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "ETHF",
    c_base: "ETHF",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "USDD_USDT",
    pair_b: "ETHF_USDT",
    pair_c: "ETHF_USDD",
    triangular_pair: "ETHF_USDD ETHF_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "DC",
    c_base: "DC",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "USDD_USDT",
    pair_b: "DC_USDT",
    pair_c: "DC_USDD",
    triangular_pair: "DC_USDD DC_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "SSV",
    c_base: "SSV",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "USDD_USDT",
    pair_b: "SSV_USDT",
    pair_c: "SSV_USDD",
    triangular_pair: "SSV_USDD SSV_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "APX",
    c_base: "APX",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "USDD_USDT",
    pair_b: "APX_USDT",
    pair_c: "APX_USDD",
    triangular_pair: "APX_USDD APX_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "AFC",
    c_base: "AFC",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "AFC_USDD",
    pair_c: "AFC_USDT",
    triangular_pair: "AFC_USDD AFC_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "CITY",
    c_base: "CITY",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "CITY_USDD",
    pair_c: "CITY_USDT",
    triangular_pair: "CITY_USDD CITY_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "ZBC",
    c_base: "ZBC",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "ZBC_USDD",
    pair_c: "ZBC_USDT",
    triangular_pair: "USDD_USDT ZBC_USDD ZBC_USDT",
  },
  {
    a_base: "USDD",
    b_base: "XEN",
    c_base: "XEN",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "XEN_USDD",
    pair_c: "XEN_USDT",
    triangular_pair: "USDD_USDT XEN_USDD XEN_USDT",
  },
  {
    a_base: "USDD",
    b_base: "HFT",
    c_base: "HFT",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "HFT_USDD",
    pair_c: "HFT_USDT",
    triangular_pair: "HFT_USDD HFT_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "OP",
    c_base: "OP",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "OP_USDD",
    pair_c: "OP_USDT",
    triangular_pair: "OP_USDD OP_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "GMX",
    c_base: "GMX",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "GMX_USDD",
    pair_c: "GMX_USDT",
    triangular_pair: "GMX_USDD GMX_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "NEAR",
    c_base: "NEAR",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "NEAR_USDD",
    pair_c: "NEAR_USDT",
    triangular_pair: "NEAR_USDD NEAR_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "ACM",
    c_base: "ACM",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "ACM_USDD",
    pair_c: "ACM_USDT",
    triangular_pair: "ACM_USDD ACM_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "JUV",
    c_base: "JUV",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "JUV_USDD",
    pair_c: "JUV_USDT",
    triangular_pair: "JUV_USDD JUV_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "ASR",
    c_base: "ASR",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "ASR_USDD",
    pair_c: "ASR_USDT",
    triangular_pair: "ASR_USDD ASR_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "PSG",
    c_base: "PSG",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "PSG_USDD",
    pair_c: "PSG_USDT",
    triangular_pair: "PSG_USDD PSG_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "TON",
    c_base: "TON",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "USDD_USDT",
    pair_b: "TON_USDT",
    pair_c: "TON_USDD",
    triangular_pair: "TON_USDD TON_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "MASK",
    c_base: "MASK",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "MASK_USDD",
    pair_c: "MASK_USDT",
    triangular_pair: "MASK_USDD MASK_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "ARG",
    c_base: "ARG",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "ARG_USDD",
    pair_c: "ARG_USDT",
    triangular_pair: "ARG_USDD ARG_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "POR",
    c_base: "POR",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "POR_USDD",
    pair_c: "POR_USDT",
    triangular_pair: "POR_USDD POR_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "APT",
    c_base: "APT",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "APT_USDD",
    pair_c: "APT_USDT",
    triangular_pair: "APT_USDD APT_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "VINU",
    c_base: "VINU",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "VINU_USDD",
    pair_c: "VINU_USDT",
    triangular_pair: "USDD_USDT VINU_USDD VINU_USDT",
  },
  {
    a_base: "USDD",
    b_base: "BAR",
    c_base: "BAR",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "BAR_USDD",
    pair_c: "BAR_USDT",
    triangular_pair: "BAR_USDD BAR_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "ATM",
    c_base: "ATM",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "ATM_USDD",
    pair_c: "ATM_USDT",
    triangular_pair: "ATM_USDD ATM_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "CEL",
    c_base: "CEL",
    a_quote: "USDT",
    b_quote: "USDT",
    c_quote: "USDD",
    pair_a: "USDD_USDT",
    pair_b: "CEL_USDT",
    pair_c: "CEL_USDD",
    triangular_pair: "CEL_USDD CEL_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "BITCI",
    c_base: "BITCI",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "BITCI_USDD",
    pair_c: "BITCI_USDT",
    triangular_pair: "BITCI_USDD BITCI_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "BFT",
    c_base: "BFT",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "BFT_USDD",
    pair_c: "BFT_USDT",
    triangular_pair: "BFT_USDD BFT_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "VGX",
    c_base: "VGX",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "VGX_USDD",
    pair_c: "VGX_USDT",
    triangular_pair: "USDD_USDT VGX_USDD VGX_USDT",
  },
  {
    a_base: "USDD",
    b_base: "PORTO",
    c_base: "PORTO",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "PORTO_USDD",
    pair_c: "PORTO_USDT",
    triangular_pair: "PORTO_USDD PORTO_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "LAZIO",
    c_base: "LAZIO",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "LAZIO_USDD",
    pair_c: "LAZIO_USDT",
    triangular_pair: "LAZIO_USDD LAZIO_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "BONK",
    c_base: "BONK",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "BONK_USDD",
    pair_c: "BONK_USDT",
    triangular_pair: "BONK_USDD BONK_USDT USDD_USDT",
  },
  {
    a_base: "USDD",
    b_base: "OG",
    c_base: "OG",
    a_quote: "USDT",
    b_quote: "USDD",
    c_quote: "USDT",
    pair_a: "USDD_USDT",
    pair_b: "OG_USDD",
    pair_c: "OG_USDT",
    triangular_pair: "OG_USDD OG_USDT USDD_USDT",
  },
  {
    a_base: "ETH",
    b_base: "ETHW",
    c_base: "ETHW",
    a_quote: "USDD",
    b_quote: "USDD",
    c_quote: "ETH",
    pair_a: "ETH_USDD",
    pair_b: "ETHW_USDD",
    pair_c: "ETHW_ETH",
    triangular_pair: "ETHW_ETH ETHW_USDD ETH_USDD",
  },
];

async function step_1(): Promise<DepthInfo | { "realRatePerc < -1": string }> {
  // Get Latest Surface Prices
  //const prices_json: PricesJson[] | null = await axios.get(prices_url);

  async function extractData(): Promise<any> {
    try {
      const response = await axios.get(
        "https://api.poloniex.com/markets/ticker24h"
      );

      const result: any = {};

      response.data.forEach((element: any) => {
        const { symbol, ask, bid } = element;

        result[symbol] = {
          lowestAsk: ask,
          highestBid: bid,
        };
      });

      return result;
    } catch (error) {
      console.error("Erreur lors de la récupération des données :", error);
      return null;
    }
  }
  const prices_json = await extractData();
  //const response = await axios.get<PricesJson>("http://localhost:3000/prices");
  //const prices_json = response.data;

  for (const t_pair of structured_pairs) {
    const prices_dict = func_arbitrage.getPriceForTPair(t_pair, prices_json);
    const surface_dict = func_arbitrage.calcTriangularArbSurfaceRate(
      t_pair,
      prices_dict
    );

    if (Object.keys(surface_dict).length > 0) {
      real_rate_dict = await func_arbitrage.getDepthFromOrderbook(surface_dict);
      if (Object.keys(real_rate_dict).length > 1) {
        console.log("real rate", real_rate_dict);
        await insertDocument("real_rate_dict_collection", {
          real_rate_dict,
          timestamp: new Date(),
        });
      }
    }
  }
  return real_rate_dict;
}

async function insertDocument(
  collectionName: string,
  document: any
): Promise<void> {
  try {
    await client.connect();
    const db = client.db(dbName);
    const collection = db.collection(collectionName);
    await collection.insertOne(document);
    console.log("Document inserted successfully");
  } catch (error) {
    console.error("Error inserting document:", error);
  } finally {
    await client.close();
  }
}

if (require.main === module) {
  step_1();
  setInterval(step_1, 170);

  app.listen(port, () => {
    console.log(`Serveur démarré sur le port ${port}`);
  });
}
